# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-11-19 04:01-0600\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n"
"%100>=11 && n%100<=14)? 2 : 3);\n"

#: exceptions.py:23
msgid "Something went wrong"
msgstr "Что-то пошло не так."

#: exceptions.py:51
msgid "Operation is in progress."
msgstr "Операция в процессе обработки."

#: exceptions.py:69
#, python-brace-format
msgid "The {service} service reported a failure."
msgstr "Сервис {service} сообщил об ошибке."

#: exceptions.py:77
#, python-brace-format
msgid ""
"The {service} service is unavailable at the moment. Please try again later."
msgstr "Сервис {service} в данный момент недоступен. Пожалуйста, повторите позже."

#: exceptions.py:85
msgid "Operation with user certificate level ADVANCED not allowed."
msgstr "Операция с пользователем, чей сертификат уровня ADVANCED, не разрешена."

#: exceptions.py:127
msgid "A signing session is already in progress."
msgstr "Сессия цифровой подписи уже в процессе."

#: exceptions.py:133
msgid "No signing session found."
msgstr "Сессия цифровой подписи не найдена"

#: exceptions.py:144
msgid "Invalid parameters."
msgstr "Некорректные параметры."

#: exceptions.py:153
#, python-brace-format
msgid "Invalid value for parameter {param}."
msgstr "Некорректное значение параметра {param}."

#: exceptions.py:163
msgid "Invalid ID code."
msgstr "Некорректный ИД код."

#: exceptions.py:174
msgid "User not registered in the service."
msgstr "Пользователь не зарегистрирован в системе."

#: exceptions.py:182
msgid "The signing operation was canceled by the user."
msgstr "Операция цифровой подписи была отменена пользователем."

#: exceptions.py:195
msgid "The signing operation timed out."
msgstr "Время ожидания подтверждения цифровой подписи истекло."

#: exceptions.py:206
msgid "The container has been already signed by the user."
msgstr "Этот документ был уже подписан этим пользователем."

#: mobileid/i18n.py:13 smartid/i18n.py:12
msgid "Authenticate"
msgstr "Авторизуйтесь"

#: mobileid/i18n.py:14 smartid/i18n.py:13
msgid "Sign"
msgstr "Подпишите"

#: signing/views.py:190
msgid "Internal server error"
msgstr "Внутренняя ошибка сервера"

#: smartid/apps.py:7
msgid "SmartIDService"
msgstr "Сервис SmartID"
